DEFRA/phi-frontend

src/server/home/index.njk
src/server/locales/home/en_cy.json
src/server/locales/home/en_gb.json
src/server/locales/import-confirmation/en_gb.json
src/server/locales/plant-health/en_gb.json
src/server/locales/purpose-of-visit/en_gb.json
src/server/plant-health/import-confirmation/service-unavailable.njk

Issues relating to content in static pages are fixed

Issues relating to content in static pages are fixed

---

src/client/assets/stylesheets/core/_all.scss
src/server/common/templates/partials/get-help.njk
src/server/home/index.njk
src/server/locales/home/en_cy.json
src/server/locales/home/en_gb.json

JIRA Ticket:  PHIDP-73 start page ui fixes

start page ui fixes

---

src/server/common/components/breadcrumbs/template.njk
src/server/common/templates/partials/get-help.njk

fix get help section font issue

fix get help  font issue

---

src/server/locales/home/en_cy.json
src/server/locales/home/en_gb.json
src/server/locales/import-confirmation/en_cy.json
src/server/locales/import-confirmation/en_gb.json
src/server/locales/purpose-of-visit/en_cy.json
src/server/locales/purpose-of-visit/en_gb.json

static page content issues on errors

static page content issues on errors

---

src/server/home/index.njk
src/server/locales/import-confirmation/en_gb.json
src/server/locales/purpose-of-visit/en_gb.json

content verification changes

---

src/api/search/controller.js
src/config/index.js
src/server/plant-health/import-confirmation/controller.js
src/server/plant-health/search/controller.js
src/server/plant-health/search/index.njk

use configured variables for the URL from cdp-app-config

use configured variables for the URL

---

src/server/home/controller.js
src/server/locales/format/en_cy.json
src/server/locales/format/en_gb.json
src/server/plant-health/country-search/controller.js
src/server/plant-health/format/controller.js
src/server/plant-health/format/index.js
src/server/plant-health/format/index.njk
src/server/plant-health/search/index.njk
src/server/router.js

format page

---

src/config/index.js
src/server/common/templates/partials/identity.njk
src/server/locales/plant-details/en_cy.json
src/server/locales/plant-details/en_gb.json
src/server/plant-health/country-search/controller.js
src/server/plant-health/format/index.njk
src/server/plant-health/plant-details/controller.js
src/server/plant-health/plant-details/index.js
src/server/plant-health/plant-details/index.njk
src/server/plant-health/search/controller.js
src/server/plant-health/search/index.njk

plant details API integration

---

src/server/locales/plant-details/en_cy.json
src/server/locales/plant-details/en_gb.json
src/server/plant-health/format/controller.js
src/server/plant-health/plant-details/index.njk
src/server/plant-health/search/index.njk

Import rules INNS and search optimise for faster results

Import rules INNS and search optimise for faster results

---

src/config/index.js
src/server/common/templates/layouts/page.njk
src/server/common/templates/partials/identity.njk
src/server/common/templates/partials/import-rules.njk
src/server/home/controller.js
src/server/locales/country-search/en_cy.json
src/server/locales/country-search/en_gb.json
src/server/locales/format/en_cy.json
src/server/locales/format/en_gb.json
src/server/locales/plant-details/en_cy.json
src/server/locales/plant-details/en_gb.json
src/server/locales/search/en_cy.json
src/server/locales/search/en_gb.json
src/server/plant-health/controller.js
src/server/plant-health/country-search/controller.js
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/controller.js
src/server/plant-health/import-confirmation/controller.js
src/server/plant-health/plant-details/controller.js
src/server/plant-health/plant-details/index.njk
src/server/plant-health/purpose-of-visit/controller.js
src/server/plant-health/search/controller.js
src/server/plant-health/search/index.njk

search observations and plant page pest details filtering

search observations and plant page pest details filtering

---

src/server/plant-health/country-search/controller.js
src/server/plant-health/country-search/index.njk
src/server/plant-health/search/index.njk

fix 403 forbidden issue and country search redirection issue

fix 403 forbidden issue and country search

---

src/server/locales/pest-details/en_gb.json

Content changes

---

src/config/index.js
src/server/common/templates/partials/identity_pest.njk
src/server/plant-health/format/controller.js
src/server/plant-health/pest-search/controller.js

1.Sorting in plant inbibitors
2.Photurl of pest updated and added no photo case too -PHIDP-58

Pest changes

---

src/config/index.js
src/server/plant-health/pest-search/controller.js

Page error fix

---

src/server/plant-health/pest-search/controller.js

1.Removed the photoURL in pest details page

removed the photoURL code

---

src/config/index.js
src/server/common/templates/partials/identity_pest.njk
src/server/locales/pest-details/en_gb.json
src/server/plant-health/pest-search/controller.js

1.Eppo code fix
2.PHIDP -56
3.PHIDP -61

Eppo code fix

---

src/server/common/templates/partials/identity_pest.njk
src/server/plant-health/pest-details/index.njk
src/server/plant-health/pest-search/controller.js

1.Observation 
2.Page title changes

Pest observation changes

---

src/config/index.js
src/server/common/templates/partials/identity_pest.njk
src/server/plant-health/pest-details/index.njk
src/server/plant-health/pest-search/controller.js
src/server/plant-health/search/index.njk

1.Heading structure changes in Pest
2.Not available added to date format issues
3.Some AX fixes added.

Headingstructure changes

---

src/server/plant-health/country-search/controller.js
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/index.njk
src/server/plant-health/import-confirmation/controller.js
src/server/plant-health/search/controller.js
src/server/plant-health/search/index.njk

fix retaining values for both search and country search

fix retaining values for both search and country search

---

src/server/common/templates/partials/identity_pest.njk
src/server/locales/plant-details/en_gb.json
src/server/plant-health/country-search/index.njk
src/server/plant-health/pest-details/index.njk
src/server/plant-health/search/index.njk

1.phi-407 -fixed
2.phi 404 - fixed
3.phi 401 -fixed

Accessibility and observations

---

src/config/index.js
src/partially-prohibited.njk
src/server/common/templates/partials/identity.njk
src/server/common/templates/partials/identity_pest.njk
src/server/common/templates/partials/import-rules.njk
src/server/common/templates/partials/partially-prohibited-eusl-import-rules.njk
src/server/common/templates/partials/partially-prohibited-non-eusl-import-rules.njk
src/server/common/templates/partials/partially-prohibited-with-exceptions.njk
src/server/common/templates/partials/unprohibited-eusl-import-rules.njk
src/server/common/templates/partials/unprohibited-non-eusl-import-rules.njk
src/server/common/templates/partials/{% if (data.result.annex11RulesArr.nunjucks
src/server/plant-health/country-search/index.njk
src/server/plant-health/pest-search/controller.js

1. Document format changes
2. Heading structure for plant details

Pest observation

---

src/server/common/templates/partials/identity_pest.njk
src/server/plant-health/country-search/index.njk
src/server/plant-health/search/index.njk

Observations fixed
1.PHIDP - 401
2.PHIDP-420
3.PHIDP-410
4.PHIDP-404
5.PHIDP-378
6.PHIDP-355

Observation fixes

---

src/config/index.js
src/partially-prohibited.njk
src/server/common/templates/partials/identity.njk
src/server/common/templates/partials/identity_pest.njk
src/server/common/templates/partials/import-rules.njk
src/server/common/templates/partials/partially-prohibited-eusl-import-rules.njk
src/server/common/templates/partials/partially-prohibited-non-eusl-import-rules.njk
src/server/common/templates/partials/partially-prohibited-with-exceptions.njk
src/server/common/templates/partials/unprohibited-eusl-import-rules.njk
src/server/common/templates/partials/unprohibited-non-eusl-import-rules.njk
src/server/common/templates/partials/{% if (data.result.annex11RulesArr.nunjucks
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/index.njk
src/server/plant-health/plant-details/index.njk
src/server/plant-health/search/index.njk

Issues fixed
1.Pest details page -fixed
2.stopping scroll
3.country search keydown
4.Bracket issue of plant in format and plant details page

Aug 06 fix

---

src/server/plant-health/country-search/index.njk
src/server/plant-health/search/index.njk

Issues fixed
1.Pest details page -fixed
2.stopping scroll
3.country search keydown
4.Bracket issue of plant in format and plant details page

Removed console.log

---

src/server/plant-health/country-search/index.njk

bracket issue

---

src/server/home/controller.js
src/server/plant-health/pest-search/controller.js
src/server/plant-health/pest-search/index.njk
src/server/plant-health/purpose-of-visit/controller.js

1.Error in title page
2. Session dat acleared when user enters newly

pest pbservation -64

---

src/config/index.js
src/server/common/templates/partials/identity.njk
src/server/common/templates/partials/identity_pest.njk
src/server/locales/pest-details/en_gb.json
src/server/locales/plant-details/en_gb.json
src/server/plant-health/controller.js
src/server/plant-health/pest-search/controller.js
src/server/plant-health/pest-search/index.njk
src/server/plant-health/plant-details/index.njk

PHIDP -62
PHIDP-459
PHIDP-451
PHIDP -439
PHIDP-446

content updates

---

src/server/common/templates/partials/404.njk
src/server/common/templates/partials/500.njk
src/server/common/templates/partials/get-help.njk
src/server/common/templates/partials/identity_pest.njk
src/server/locales/pest-details/en_gb.json
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/index.njk
src/server/plant-health/import-confirmation/index.njk
src/server/plant-health/index.njk
src/server/plant-health/pest-search/index.njk
src/server/plant-health/search/index.njk

Accessibility low priority changes

---

src/client/assets/javascripts/application.js
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/index.njk
src/server/plant-health/import-confirmation/controller.js
src/server/plant-health/plant-details/index.njk
src/server/plant-health/search/controller.js
src/server/plant-health/search/index.njk

fix back and forth, exact match and invalid selection issues  plant autocomplete search

fix back and forth, exact match and invalid selection issues  plant autocomplete search

---

src/server/common/templates/layouts/page.njk

Sept02 obs

---

src/client/assets/javascripts/pest-search.js
src/config/index.js

1.Space issue solved in pest search

Sort issue pest search

---

src/client/assets/javascripts/country-search.js
src/server/plant-health/country-search/controller.js
src/server/plant-health/pest-search/controller.js
src/server/plant-health/search/controller.js

plant, pest & country search no result found issue fixes

plant, pest & country search no result found issue fixes

---

src/server/home/controller.js
src/server/plant-health/pest-search/controller.js

pest search fixes

---

src/server/common/templates/partials/import-rules.njk
src/server/locales/plant-details/en_cy.json
src/server/locales/plant-details/en_gb.json

fix 527 hybrid text issue

---

src/config/index.js
src/server/common/templates/partials/404.njk
src/server/common/templates/partials/500.njk
src/server/common/templates/partials/get-help.njk
src/server/plant-health/country-search/index.njk
src/server/plant-health/format/index.njk
src/server/plant-health/import-confirmation/index.njk
src/server/plant-health/index.njk
src/server/plant-health/pest-details/index.njk
src/server/plant-health/pest-search/index.njk
src/server/plant-health/plant-details/index.njk
src/server/plant-health/search/index.njk

PHIDP-582,578,581_contentchanges

PHIDP-582,578,581_contentchanges

---

src/server/common/templates/layouts/page.njk

Added cookie page in the footer

Added cookie page in the footer

---

src/server/cookies/index.njk
src/server/locales/cookie/en_gb.json

1.Back link update
2.Expiry date changed to 1 year
3.Added phi analytic cookie in cookie page

cookies back link and content update

---

src/server/cookies/index.js
src/server/cookies/index.njk
src/server/index.js

1.Login page removed
2.Auth strategy removed in cookies
3.Phi-cookies removed in cookie page

Login page removal

---

src/config/nunjucks/context/build-navigation.test.js
src/server/plant-health/pest-details/index.njk
src/server/plant-health/plant-details/index.njk

1.Find another plant pest route change

Route change

---

src/client/assets/javascripts/cookie-functions.js

GAdummy tags

---

src/server/common/helpers/errors.js

Reverts DEFRA/phi-frontend#144

Revert "security headers"

---

src/server/index.js

Google Analytics allow origin & Cross-origin CORP

---

src/server/plant-health/country-search/index.njk

changing format from label to inset-text

country search inset text
